sudo: required
dist: cosmic
before_install:
- sudo apt-get -qq update 
- sudo apt-get install -y --no-install-recommends texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-science
- sudo apt-get install -y --no-install-recommends xzdec
script:
- source ./bin/conf.sh 
- make clean all
